a = input (' Digite algo: ')
print ('O tipo primitivo desse valor é ', type(a))
print (' Só tem espaços?',a.isspace())
print('Essa letra é maiúscula? ', a.isupper())
print ('Está em letra minúscula?', a.islower())
print ('Está captalizada? (Começa com letra maíscula)',a.istitle())
print ('é uma letra? ', a.isalpha())
print ('é um número?', a.isnumeric())