n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro valor: '))
print('A soma de é igual a {}'.format(n1+n2))
print ('A subtração é igual a {}'.format(n1-n2))
print ('A multiplacação é igual a {}'.format(n1*n2))
print (' A divisão é igual a {}'.format(n1/n2))
print (' A potenciação é igual a {}'.format(n1**n2))
print ('A divisão inteira é igual a {}'.format (n1//n2))
print ('o resto da divisão é igual a {}'.format(n1%n2))